#cloud-config
package_update: true
package_upgrade: true

packages:
  - yum-utils
  - git
  - vim
  - tmux

runcmd:
  - >
    echo -e "n\np\n1\n\n\nw" | fdisk /dev/nvme1n1
  - mkfs -t xfs /dev/nvme1n1p1
  - dnf update -y